export enum MemoryType {
  NbProductToPayForAdvance = 1,
  PlayerNbProducts,
  IsOffSeason,
  ProductChoosen,
  ShipChoosen,
  NbProductGiven,
  LawsuitAdvanced,
  NbTimeAdvancedInLawsuit,
  NbSwaps,
  IsProductReturn,
  NbProductsDonated,
  IsDonationInProgress,
  NbDonations,
  NbCardsDraw,
  BasicActionChoosen,
  IsBuildInProgress,
  NextRules,
  ComputedActions,
  NbProductStealed,
  AlliancePay,
  ProcessedBonuses,
  MovesOnLawsuitWin,
}
