export enum MemoryType {
  NbProductToPayForAdvance = 1,
  PlayerNbProducts,
  IsOffSeason,
  ProductChoosen,
  ShipChoosen,
  NbProductGiven,
  LawsuitAdvanced,
  NbTimeAdvancedInLawsuit,
  NbSwaps,
  IsProductReturn,
  NbProductsDonated,
  IsDonationInProgress,
  BasicActionChoosen,
  IsBuildInProgress,
  NextRules,
}
