export enum RuleId {
  ChooseFirstProduct = 1,
  AdvanceInkJar,
  PayProductForAdvance,
  ChooseAction,
  BasicAction,
  SpecialAction,
  Choose2Product,
  Choose1Product,
  AdvanceAgainInLawsuit,
  ResolveLawsuit,
  AdvanceLawsuitAction,
  DrawSpecialActionCardAction,
  EarnPrestigeAction,
  GainLetterAction,
  OffSeasonTakeBell,
  OffSeasonPayForAlliance,
  OffSeasonGetShipsBonuses,
  OffSeasonGetPrestigeBonuses,
  OffSeasonChangeSpecialCards,
  OffSeasonReactivateFactories,
  OffSeasonReturnBell
}
