export enum RuleId {
  ChooseFirstProduct = 1,
  AdvanceInkJar,
  PayProductForAdvance,
  ChooseAction,
  BasicAction,
  Choose2Product,
  Choose1Product,
  AdvanceAgainInLawsuit,
  ResolveLawsuit,
  AdvanceLawsuitAction,
  BuildFactoryAction,
  CourtRulingAction,
  DonationAction,
  DrawSpecialActionCardAction,
  EarnPrestigeAction,
  FormAllianceAction,
  GainLetterAction,
  GiftAction,
  ProductionAction,
  ProductSwapAction,
  PurchaseShipAction
}
