export enum ActionType {
  Production = 1,
  AdvanceLawsuit,
  BuildFactory,
  Donation,
  DrawSpecialActionCard,
  EarnPrestige,
  OpponentEarnPrestige,
  FormAlliance,
  GainLetter,
  Gift,
  ProductSwap,
  PurchaseShip,
  CourtRuling,
  ReturnFactory,
  Piracy,
  Split,
  Multiple,
  ResolveLawsuit,
  ChooseSpecialActionCard,
  PayToPerformActionAgain
}
