export enum SpecialAction {
  SpecialAction1 = 1,
  SpecialAction2,
  SpecialAction3,
  SpecialAction4,
  SpecialAction5,
  SpecialAction6,
  SpecialAction7,
  SpecialAction8,
  SpecialAction9,
  SpecialAction10,
  SpecialAction11,
  SpecialAction12,
  SpecialAction13,
  SpecialAction14,
  SpecialAction15,
  SpecialAction16,
  SpecialAction17,
  SpecialAction18,
  SpecialAction19,
  SpecialAction20,
  SpecialAction21,
  SpecialAction22,
  SpecialAction23,
  SpecialAction24
}
